### ISSUE TITLE
Facebook SDK v5.4.1

### ISSUE THREAD

**Issue by lassana** [xamarin/FacebookComponents#143]
"Log In with Facebook" doesn't work on iOS 13 Beta with the latest [Xamarin.Facebook.iOS v5.0.2](https://www.nuget.org/packages/Xamarin.Facebook.iOS/): `LoginManager.LogIn` always returns a cancelled result. The fix for this [is available in v5.4.1](https://github.com/facebook/facebook-objc-sdk/issues/1013#issuecomment-523695602). Since iOS 13 is going to be released soon, we really need an update of Xamarin bindings.

**Comment by opacitychris** [comment]
Experiencing the same issue today.

**Comment by noka03** [comment]
IOS13 is now released, Im having the same issues can we get a new version of this pushed to NuGet referencing 5.4.1 or above.

**Comment by garie** [comment]
+1, this should be high priority as it will prevent all iOS 13 users from logging in

**Comment by zeldages** [comment]
I'm also battling with this one. A fix would be greatly appreciated.

**Comment by AlyElHaddad** [comment]
Looks like everybody was forced to upgrade to the latest iOS SDK in the last 24 hours. This needs to be addressed ASAP. All releases are broken. This issue seems to have been resolved in version 5.6.0 as per stated in [facebook-objc-sdk changelog](https://github.com/facebook/facebook-objc-sdk/blob/master/CHANGELOG.md#560). Corresponding bindings libraries needs to be updated.

**Comment by jefftindall** [comment]
Same issue here.  Hope it gets escalated soon.

**Comment by SotoiGhost** [comment]
We are working on this, hope can be released in the following days.

**Comment by AntRemo** [comment]
I know 4.35.0 is not the latest, and perhaps there is a failing use case I have not come across, but I just tested logging in, on iOS 13.0, via 4.35.0 and it appears to be working. This may be an option until the proper fix is released.

**Comment by AlyElHaddad** [comment]
> I know 4.35.0 is not the latest, and perhaps there is a failing use case I have not come across, but I just tested logging in, on iOS 13.0, via 4.35.0 and it appears to be working. This may be an option until the proper fix is released.

Just tested logging in on iOS 13.0 (iPhone 11 Pro Max Simulator ) after this release, and it does NOT appear to be working. The same issue persisted.

**Comment by StefAnglr** [comment]
I see this has been moved back to "needs triage." Should we be looking for alternative libraries?

**Comment by MahmoudHafezElsayed** [comment]
Same issue I faced

**Comment by StefAnglr** [comment]
@AntRemo Can you share your login code that works on the older SDK? I also am not seeing 4.35 work on iOS 13, using a real device.

**Comment by SotoiGhost** [comment]
This update is still a high priority, but we have a trigger that moves it back to Triage. For now, I'll leave it there, but this is something we are working on.

**Comment by StefAnglr** [comment]
Thanks, sorry for the overreaction - given the timing it looked like the move might have happened in response to the comment about 4.35 working.

**Comment by AntRemo** [comment]
@AlyElHaddad @StefAnglr sure

I just tested with **iPhone 11 Pro Max iOS 13.0**

Below is my code. Please let me know if you have any questions.

`       
public Task<AuthResult> Authenticate()
{
    var tcs = new TaskCompletionSource<AuthResult>();

    try
    {
        var window = UIApplication.SharedApplication.KeyWindow;
        var vc = window.RootViewController;
        while (vc.PresentedViewController != null)
        {
            vc = vc.PresentedViewController;
        }

        var manager = new LoginManager();
        manager.LogOut();
        manager.LoginBehavior = LoginBehavior.SystemAccount;
        manager.LogInWithReadPermissions(new string[] { "public_profile", "email" },
            vc,
            (result, error) =>
            {
                if (error != null)
                {
                    tcs.TrySetException(new ApplicationException(error.LocalizedDescription));
                    return;
                }

                if (result == null || result.IsCancelled)
                {
                    tcs.TrySetCanceled();
                }
                else
                {
                    Task.Run(() => { CallGraphForDetails(tcs, result); });
                }
            });
    }
    catch (Exception ex)
    {
        tcs.TrySetException(ex);
    }

    return tcs.Task;
} 

`

**Comment by StefAnglr** [comment]
@AntRemo Thank you for sharing your code. The only significant difference I noticed between yours and mine is that you're using the synchronous `LoginWithReadPermissions`, while I was using `LoginWithReadPermissionsAsync`. Switching to the synchronous version didn't seem to make a difference.

Is it possible that you're still building against the iOS 12 SDK? Our last published version, built before the Xcode and Visual Studio updates, still works on iOS 13.

**Comment by AntRemo** [comment]
My pleasure @StefAnglr 

Here is my version info

**Xcode**
Version 11.0 (11A420a)

**Xamarin.iOS**
Version: 13.2.0.42 (Visual Studio Professional)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

I'm about to upgrade to **Xcode 11.1 GM seed** given all of the bug fixes.

Hope that helps and please let me know if you have any other questions. Also, maybe resetting the simulator and/or clean of the solution may help. 

Good Luck!

**Comment by AntRemo** [comment]
@StefAnglr 

I thought it also is worth mentioning that in my AppDelegate I also have the following code

private static bool ProcessOpenUrl(UIApplication application, NSUrl url, string sourceApplication, NSObject annotation)
{
	        if (ApplicationDelegate.SharedInstance.OpenUrl(application, url, sourceApplication, annotation))
	        {
	            return true;
	        }
}

**Comment by CMorooney** [comment]
adding onto this pile -- we're stuck not being able to release our app until this is resolved since our users couldn't auth with facebook on their iOS 13 devices. Are we still expecting an update soon?

**Comment by AlyElHaddad** [comment]
@AntRemo thanks for your reply. Our implementation is almost the same as this. We also have the `OpenUrl` part; but yet, we still cannot authenticate using Facebook.

**Comment by AntRemo** [comment]
@AlyElHaddad sorry to hear.

Lastly my info.plist has
```xml
 <!--Facebook Auth-->
  <key>FacebookAppID</key>
  <string>MyNumericAppId</string>
  <key>FacebookDisplayName</key>
  <string>MyAppName</string>
  <key>LSApplicationQueriesSchemes</key>
  <array>
    <string>fbapi</string>
    <string>fb-messenger-share-api</string>
    <string>fbauth2</string>
    <string>fbshareextension</string>
  </array>

**Comment by AlyElHaddad** [comment]
@AntRemo we also have this. The problem came out only after the latest iOS SDK update.

**Comment by AntRemo** [comment]
@AlyElHaddad I understand. I also have a iPhone 11 Pro and I'm able to login.

Just trying to think what else could be different.

**Comment by winstongubantes** [comment]
Is there any workaround? i am unable to release because of this issue.

**Comment by winstongubantes** [comment]
after 3 hours of head scratching, found a workaround i just reverted my VS2019 to version 16.2.4 and reverted also the XCode on mac to version 10.2.1, and everything works as usual. Hope it helps.

**Comment by awatertrevi** [comment]
Any update on this? We're unable to release as well...

**Comment by SotoiGhost** [comment]
Guys, letting you know that Facebook for iOS v5.6.0 has been pushed to NuGet. If something happens, please, let me know.

**Comment by StefAnglr** [comment]
Worked for us! Thanks for the update!

**Comment by awatertrevi** [comment]
Thank you so much!

**Comment by AlyElHaddad** [comment]
At last! Thanks for your efforts!

**Comment by opacitychris** [comment]
Unfortunately, I've had no luck today.   Confirmed I've got 5.6.0 installed.

When my app is installed on an iOS13 device or simulator, clicking sign-in does nothing.  Returns a result.isCancelled=true

When my app is installed on an iOS12 device or simulator, it works as usual.

I've confirmed i have the appropriate plist entries and have confirmed my AppDelegate functions are there (as mentioned, its working under iOS12)

All ears if anyone has any advice.... i have 30,000 users that arent happy.

**Comment by lassana** [comment]
@opacitychris there must be something wrong with your environment, v5.6.0 works just fine. As usual, try clean/rebuild, deleting bin/obj and NuGet cache etc.

**Comment by opacitychris** [comment]
True, ive done clean/re-build, rebooted, re-installed all nuget packages but there are a few other things I will try.  Thanks for the reminder.

**Comment by opacitychris** [comment]
Getting the xcode 11.1 GM seed and getting everything up to latest versions eventually solved my issue.  It may have been clearing the bin/obj as well while those were installed.

Either way, all better.  Thanks.

**Comment by nhdanh** [comment]
need update sdk to newest version on Android. I couldn found any sample project for xamarin android binding ? Need one to help me config it !

**Comment by awatertrevi** [comment]
After releasing this to our users we noticed that the "Log in with the Facebook app" button does not seem to work (the login with phone or email button does).

Here is a small video:

https://www.youtube.com/watch?v=g9VET5BuG28&feature=youtu.be

The code for our login button renderer is as follows:

```
public class FacebookLoginButtonRenderer : ViewRenderer<Button, LoginButton>
    {
        private FacebookLoginButton _facebookLoginButton => (FacebookLoginButton)Element;

        private readonly List<string> _permissions = new List<string> { "email" }; // TODO: Add these to Forms control.

        private LoginButton _loginView;

        private bool _hasInitialized;

        protected override void OnElementChanged(ElementChangedEventArgs<Button> e)
        {
            base.OnElementChanged(e);

            if (!_hasInitialized)
            {
                _facebookLoginButton.Logout += LogoutRequested;

                _loginView = new LoginButton(new CGRect(48, 0, 256, 46))
                {
                    Permissions = _permissions.ToArray()
                };

                _loginView.SetAttributedTitle(new NSAttributedString("Doorgaan met Facebook"), UIControlState.Normal); // TODO: Add button text to control.

                _loginView.Completed += LoginCompleted;

                if (_loginView != null)
                    SetNativeControl(_loginView);

                _hasInitialized = true;
            }
        }

        private void LogoutRequested(object sender)
        {
            using (var loginManager = new LoginManager())
                loginManager.LogOut();
        }

        private void LoginCompleted(object sender, LoginButtonCompletedEventArgs e)
        {
            if (e.Error != null)
                _facebookLoginButton.LoginFailed.Invoke(e.Error.Description);

            if (e.Result.IsCancelled)
                return;

            _facebookLoginButton.LoginCompleted.Invoke(e.Result.Token.TokenString);
        }
```

I understand that this could possibility be unrelated to this issue; however its something that appeared after this update.
